"""TF-IDF feature extraction, ported from ezr's `tmTokenize`..`tmTfidf`.

The vendored `ezr.py` needs Python 3.12 (it uses PEP 695 `type` statements)
while this project runs on 3.11, so the pipeline is reimplemented here rather
than imported. `validate.py` asserts the port is exact against a reference
dump generated by running the untouched vendored file under 3.12.

Two places where a faithful port matters more than it looks:

* Column order. `vocab` is sorted by descending TF-IDF score and `sorted` is
  stable, so words with equal scores keep the insertion order of the document
  frequency table -- which is first-appearance order scanning documents in
  file order. Get that wrong and the 100th feature differs.
* Accumulation order. The score of a word is summed document by document, as
  ezr does, instead of the algebraically equal `total_count * log(N/df)`.
  The two differ in the last ulp, which is enough to reorder tied features.

Feature extraction is unsupervised -- labels never enter it -- so running it
once over the whole corpus leaks nothing into the active-learning loop.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from math import log
from pathlib import Path

import numpy as np

VENDOR_RESOURCES = Path(__file__).parent / "vendor" / "resources" / "text"

WORD = re.compile(r"\b[a-zA-Z]+\b")
MIN_WORD_LEN = 3  # ezr keeps words with len(w) > 2


@dataclass(frozen=True)
class Features:
    X: np.ndarray  # (n_docs, n_features) int32 term counts
    vocab: list[str]


def _load_resource(name: str) -> set[str]:
    """Ports ezr `_tm_load`: newline-separated, lowercased, blanks dropped."""
    try:
        text = (VENDOR_RESOURCES / name).read_text()
    except OSError:
        text = ""
    return {w.strip().lower() for w in text.splitlines() if w.strip()}


def _stem1(w: str, sufs: list[str], cache: dict[str, str], n: int = 1) -> str:
    """Ports ezr `_tm_stem1`. Strips at most one suffix (n defaults to 1)."""
    if w in cache or n <= 0:
        return cache.setdefault(w, w)
    for s in sufs:
        if w.endswith(s) and len(w) > len(s) + 2:
            c = w[: -len(s)]
            if len(c) >= 2 and len(c) >= len(w) * 0.5:
                return cache.setdefault(w, _stem1(c, sufs, cache, n - 1))
    return cache.setdefault(w, w)


def tokenize(texts: list[str]) -> list[list[str]]:
    return [
        [w for w in WORD.findall(str(t).lower()) if len(w) >= MIN_WORD_LEN]
        for t in texts
    ]


def drop_stopwords(docs: list[list[str]]) -> list[list[str]]:
    stop = _load_resource("stop_words.txt")
    return [[w for w in d if w not in stop] for d in docs]


def stem(docs: list[list[str]]) -> list[list[str]]:
    sufs = sorted(_load_resource("suffixes.txt"), key=len, reverse=True)
    cache: dict[str, str] = {}  # shared across documents, as in ezr
    return [[_stem1(w, sufs, cache) for w in d] for d in docs]


def tfidf(docs: list[list[str]], top: int = 100) -> Features:
    """Term counts restricted to the `top` words by corpus-wide TF-IDF."""
    tf: list[dict[str, int]] = []
    df: dict[str, int] = {}
    for words in docs:
        counts: dict[str, int] = {}
        for w in words:
            counts[w] = counts.get(w, 0) + 1
        for w in counts:  # insertion order = first appearance in this document
            df[w] = df.get(w, 0) + 1
        tf.append(counts)

    n_docs = len(docs) or 1
    idf = {w: log(n_docs / d) for w, d in df.items()}

    # Accumulated per document, in document order, matching ezr exactly.
    score = dict.fromkeys(df, 0.0)
    for counts in tf:
        for w, c in counts.items():
            score[w] += c * idf[w]

    ranked = sorted(df.keys(), key=lambda w: score[w], reverse=True)[:top]

    X = np.zeros((len(docs), len(ranked)), dtype=np.int32)
    for i, counts in enumerate(tf):
        for j, w in enumerate(ranked):
            v = counts.get(w)
            if v:
                X[i, j] = v
    return Features(X=X, vocab=ranked)


def build(texts: list[str], top: int = 100) -> Features:
    """Full pipeline: tokenize -> stopwords -> stem -> TF-IDF top-k."""
    return tfidf(stem(drop_stopwords(tokenize(texts))), top=top)


def build_sparse(texts: list[str], top: int = 5000) -> tuple["csr_matrix", list[str]]:
    """Same pipeline, sparse output, for corpora too wide to hold dense.

    The SLR corpora are 8,911 documents x 100 features -- trivially dense. The
    StableToolBench corpus is 47,058 APIs, and 100 global features cannot
    separate 765 unrelated queries, so `top` has to be far larger. At
    top=5000 a dense matrix would be 941 MB; CSR is a few tens of MB, and
    `cnb.fit`/`cnb.scores` work on it unchanged.
    """
    from scipy.sparse import csr_matrix

    docs = stem(drop_stopwords(tokenize(texts)))
    tf: list[dict[str, int]] = []
    df: dict[str, int] = {}
    for words in docs:
        counts: dict[str, int] = {}
        for w in words:
            counts[w] = counts.get(w, 0) + 1
        for w in counts:
            df[w] = df.get(w, 0) + 1
        tf.append(counts)

    n_docs = len(docs) or 1
    idf = {w: log(n_docs / d) for w, d in df.items()}
    score = dict.fromkeys(df, 0.0)
    for counts in tf:
        for w, c in counts.items():
            score[w] += c * idf[w]
    vocab = sorted(df.keys(), key=lambda w: score[w], reverse=True)[:top]
    at = {w: j for j, w in enumerate(vocab)}

    indptr, indices, data = [0], [], []
    for counts in tf:
        for w, c in counts.items():
            j = at.get(w)
            if j is not None:
                indices.append(j)
                data.append(c)
        indptr.append(len(indices))
    X = csr_matrix(
        (np.asarray(data, dtype=np.int32), np.asarray(indices), np.asarray(indptr)),
        shape=(len(docs), len(vocab)),
    )
    return X, vocab
